name: Merge Stream Files

on:
  # 定时触发配置
  schedule:
    # 这里的 cron 表示每天的 UTC 时间 00:00 运行
    # 换算成北京时间就是每天上午 8:00 准时运行
    - cron: '20 20 * * *'

  # 依然保留手动触发按钮，方便你随时测试
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Merge Script
        run: python merge_streams.py

      - name: Commit and push merged files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.io"
          git add merged_channels.txt merged_channels.m3u
          git diff --staged --quiet || git commit -m "Auto-merge special files and update timestamps [skip ci]"
          git push
